[project]
authors = ["Jermiah Joseph <jermiahjoseph98@gmail.com>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "FunCirc"
platforms = ["osx-arm64", "osx-64", "linux-64"]
version = "0.1.0"


[dependencies]
r-base = ">=4.4.1,<5"
r-essentials = ">=4.4,<5"
radian = ">=0.6.13,<0.7"
r-cli = ">=3.6.3,<4"
r-shiny = ">=1.9.1,<2"

[target.linux.tasks]
rstudio = "rstudio"

[target.osx.tasks]
rstudio = "open -a rstudio"

[tasks]
setup = {cmd = "Rscript app/dependencies.R", description = "Install dependencies"}
run = {cmd = "Rscript runApp.R"}
